### ISSUE TITLE
"Switch Sides" breaks order tokens

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#148] opened 2020-03-10 08:01 UTC
"the swap red/blue player button seems to break order token scripting? (tokens white out, display no unit of this type left on board", etc)" - discord 2020.03.10

**Comment by matanlurey** [comment] 2020-03-15 22:58
Duplicate of https://github.com/swlegion/tts/issues/13.

**Closed by matanlurey** 2020-03-15 22:58 UTC
Labels: Status: Duplicate, Type: Bug
