### ISSUE TITLE
Strike Teams heavy weapon mini gets switched out when swapping sides

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#111] opened 2019-11-10 22:58 UTC
**Describe the bug**
Reported on discord (I believe a number of times) so this is a copy/paste of the last mention:
"So I've spawned 3 proton strike teams for a game and the sabs decided to take the day off, got 2 normal gals in each squad instead..."

**To Reproduce**

**Expected behavior**

**Screenshots**

![](https://cdn.discordapp.com/attachments/388041509041340446/643172966976454666/unknown.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]

**Additional context**

**Comment by matanlurey** [comment] 2020-02-26 20:16
Duplicate of #13

**Closed by matanlurey** 2020-02-26 20:16 UTC
Labels: Severity: Major, Status: Lacks Details, Type: Bug
