### ISSUE TITLE
Deleting a condition token with a range band open creates infinite loop of errors and corrupts continuing saved games

### ISSUE THREAD

**Issue by Mitrokeegan** [swlegion/tts#87] opened 2019-10-06 05:15 UTC
**Describe the bug**
When a range band from a mine condition token was still displayed, and a player deleted the token, the range band remained but the host player got a repeating error dialog with increasing numbers until he restarted his entire client. The affected save files from after the token was deleted. 

**To Reproduce**
1. Go to new game
2. Put a condition token on the board
3. Select range band from condition token
4. Delete the condition token

**Expected behavior**
Token deletes and game remains playable 

**Screenshots**

**Desktop (please complete the following information):**
 - unknown (Stevens was host)

**Additional context**

**Comment by Mitrokeegan** [comment] 2019-10-06 05:17
Recommend Sev: Major due to ease of this happening and impact on the game (needed to restart and manually recreate the game state in a new hosting environment)

**Comment by matanlurey** [comment] 2019-10-07 22:32
Duplicate of https://github.com/swlegion/tts/issues/40.

**Closed by matanlurey** 2019-10-07 22:32 UTC
Labels: Status: Duplicate, Type: Bug
